{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-autoconfigure-adapter",
    "version": "0.5.0.3-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "nf54mbfxwvdm3obr333umrpgzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0.3-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0.3-patch-context.jar",
          "size": 120557,
          "sha512": "d27a58f89e87d57d28d06a5dc7442a377e4c58b72683674d57c9027aa132390417fa5cf67b32865f60c7cdb110b18bb9d0efee0c6443646a266317ad186de9d6",
          "sha256": "1beed8657507aa67f7e67fc5c7e919f9ea7e95faf3c3cc9e4d1aaac7892c6b4a",
          "sha1": "8a5fd7bbda0de9ba8bc314a6b4147621a186e9f9",
          "md5": "967297ccebf553deeac03372572aae45"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0.3-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0.3-patch-context.jar",
          "size": 120557,
          "sha512": "d27a58f89e87d57d28d06a5dc7442a377e4c58b72683674d57c9027aa132390417fa5cf67b32865f60c7cdb110b18bb9d0efee0c6443646a266317ad186de9d6",
          "sha256": "1beed8657507aa67f7e67fc5c7e919f9ea7e95faf3c3cc9e4d1aaac7892c6b4a",
          "sha1": "8a5fd7bbda0de9ba8bc314a6b4147621a186e9f9",
          "md5": "967297ccebf553deeac03372572aae45"
        }
      ]
    }
  ]
}
