{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-autoconfigure-adapter",
    "version": "0.5.0.6-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "oklqi7mkjfaxvglp4sinzkb5rm"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0.6-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0.6-patch-context.jar",
          "size": 120557,
          "sha512": "73fa31c0d61084e820cf56b1d2b6e7a013bdd847bacbbee69e46c5d6fcb7761e966b12b6943231ee7b7de42210b47fd4ceda00c171bb3c3623e356827b47da20",
          "sha256": "a526ac482e7bef55cb50d37b293dc6ad3977ebbfbfdc64d18dc0b7410c2e1a7b",
          "sha1": "d045fd4861a0f46f0a563904039875473b90e0ba",
          "md5": "733f0e43e9b1d4b0f9947439f83732cc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0.6-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0.6-patch-context.jar",
          "size": 120557,
          "sha512": "73fa31c0d61084e820cf56b1d2b6e7a013bdd847bacbbee69e46c5d6fcb7761e966b12b6943231ee7b7de42210b47fd4ceda00c171bb3c3623e356827b47da20",
          "sha256": "a526ac482e7bef55cb50d37b293dc6ad3977ebbfbfdc64d18dc0b7410c2e1a7b",
          "sha1": "d045fd4861a0f46f0a563904039875473b90e0ba",
          "md5": "733f0e43e9b1d4b0f9947439f83732cc"
        }
      ]
    }
  ]
}
