{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-jafu",
    "version": "0.5.0.5-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "h25zfstmy5dllda4emvo56j3lq"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.5-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.5-patch-context.jar",
          "size": 63948,
          "sha512": "ae8df01512776f85381a4cbe87f02ace1fbe54f8dc11be4080d7c0f9de8134c57d5804f71c419fea1d6db4b51f15517d7e105dd3864876edd29d688107a6d981",
          "sha256": "c2e2593bcf913532a0192442faae06bfbcc96c8d52a0f092d0f4b1fa91061617",
          "sha1": "3951fbbb5368fcf5066fb8674b685f8c54f730de",
          "md5": "c611ba68dd65ab5bc5010281f64bfe78"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.fu",
          "module": "spring-fu-autoconfigure-adapter",
          "version": {
            "requires": "0.5.0.5-patch-context"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.5-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.5-patch-context.jar",
          "size": 63948,
          "sha512": "ae8df01512776f85381a4cbe87f02ace1fbe54f8dc11be4080d7c0f9de8134c57d5804f71c419fea1d6db4b51f15517d7e105dd3864876edd29d688107a6d981",
          "sha256": "c2e2593bcf913532a0192442faae06bfbcc96c8d52a0f092d0f4b1fa91061617",
          "sha1": "3951fbbb5368fcf5066fb8674b685f8c54f730de",
          "md5": "c611ba68dd65ab5bc5010281f64bfe78"
        }
      ]
    }
  ]
}
