{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-jafu",
    "version": "0.5.0.4-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "tsx7y6tmijdijcgfxzrus4mqaa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.4-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.4-patch-context.jar",
          "size": 63948,
          "sha512": "69a36b50c6692805fd9ef6179105280bd5e2a4c5a016dc98dfca04651cec287e8c18f0eea1b379a6c893ddb25f6c15abbd5e55ed52c58896d61af39b2f96fc2b",
          "sha256": "10e5399365cdd724a717fde4625c761b204b24b0b18ac35861a85502c6439e4c",
          "sha1": "766a3b7b21b43b1b97a2aac9a1e92d2b1617ef5d",
          "md5": "a3d4d9dc55f3d00f2ee1deffd14829ec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.fu",
          "module": "spring-fu-autoconfigure-adapter",
          "version": {
            "requires": "0.5.0.4-patch-context"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.4-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.4-patch-context.jar",
          "size": 63948,
          "sha512": "69a36b50c6692805fd9ef6179105280bd5e2a4c5a016dc98dfca04651cec287e8c18f0eea1b379a6c893ddb25f6c15abbd5e55ed52c58896d61af39b2f96fc2b",
          "sha256": "10e5399365cdd724a717fde4625c761b204b24b0b18ac35861a85502c6439e4c",
          "sha1": "766a3b7b21b43b1b97a2aac9a1e92d2b1617ef5d",
          "md5": "a3d4d9dc55f3d00f2ee1deffd14829ec"
        }
      ]
    }
  ]
}
