{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-jafu",
    "version": "0.5.0.3-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.1",
      "buildId": "nf54mbfxwvdm3obr333umrpgzy"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.3-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.3-patch-context.jar",
          "size": 63948,
          "sha512": "95b4def07f493cbbe134c6bb9c309c4ed9b08ef1f0f69fa1ad93935a224b3f1ceae5bac0dd5b701c0f5bb8da1adbfda6c68ccfa2a93d81e607eaae797291ea8e",
          "sha256": "c5859c25a54cd5c10a5ab0f1b60850b455a9a5ef4d0492ac934201e566a0c9e8",
          "sha1": "d6b9ff662541ca219467dfeccbf17a2fe1bc4198",
          "md5": "5021bfdab46adcee162c56c63a078782"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.fu",
          "module": "spring-fu-autoconfigure-adapter",
          "version": {
            "requires": "0.5.0.3-patch-context"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-jafu-0.5.0.3-patch-context.jar",
          "url": "spring-fu-jafu-0.5.0.3-patch-context.jar",
          "size": 63948,
          "sha512": "95b4def07f493cbbe134c6bb9c309c4ed9b08ef1f0f69fa1ad93935a224b3f1ceae5bac0dd5b701c0f5bb8da1adbfda6c68ccfa2a93d81e607eaae797291ea8e",
          "sha256": "c5859c25a54cd5c10a5ab0f1b60850b455a9a5ef4d0492ac934201e566a0c9e8",
          "sha1": "d6b9ff662541ca219467dfeccbf17a2fe1bc4198",
          "md5": "5021bfdab46adcee162c56c63a078782"
        }
      ]
    }
  ]
}
