{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.fu",
    "module": "spring-fu-autoconfigure-adapter",
    "version": "0.5.0-patch-context",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "6xrg6s5gfzda7f2c7kft2fd4fa"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0-patch-context.jar",
          "size": 116682,
          "sha512": "6574f8bbddf4297afc0438542969e00852f3ef5742c9b4499a0103ef38d87a31e86347e0a29a57a805467c26d0cd2f1a01e645b6bb9f96974b5892cf3d0d1777",
          "sha256": "0c77f40c3fd8796f58f8b1b19f11d82429afe31f56f3c674550020784da190f0",
          "sha1": "adea054190d2c3ae291b41f497d6bfe74152e106",
          "md5": "403078955396e55373ad057fa584c899"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-autoconfigure",
          "version": {
            "requires": "2.4.0"
          },
          "excludes": [
            {
              "group": "net.objecthunter",
              "module": "exp4j"
            },
            {
              "group": "org.slf4j",
              "module": "jcl-over-slf4j"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-log"
            },
            {
              "group": "com.jcabi",
              "module": "jcabi-manifests"
            },
            {
              "group": "commons-logging",
              "module": "commons-logging"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "spring-fu-autoconfigure-adapter-0.5.0-patch-context.jar",
          "url": "spring-fu-autoconfigure-adapter-0.5.0-patch-context.jar",
          "size": 116682,
          "sha512": "6574f8bbddf4297afc0438542969e00852f3ef5742c9b4499a0103ef38d87a31e86347e0a29a57a805467c26d0cd2f1a01e645b6bb9f96974b5892cf3d0d1777",
          "sha256": "0c77f40c3fd8796f58f8b1b19f11d82429afe31f56f3c674550020784da190f0",
          "sha1": "adea054190d2c3ae291b41f497d6bfe74152e106",
          "md5": "403078955396e55373ad057fa584c899"
        }
      ]
    }
  ]
}
